modLoader="javafml"
loaderVersion="[45,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"

[[mods]]
modId="ancient_aether"
version="${file.jarVersion}"
displayName="Ancient Aether"
logoFile="ancient_aether.png"
credits= "Contributors: TunefulTurnip, Zepalesque | Translators: unroman, taizazanek"
authors="Builderdog"
description='''
An exploration Add-On that aims to completely overhaul the original mod aswell as expanding on its content.
'''
[[dependencies.ancient_aether]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.ancient_aether]]
modId="aether"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ancient_aether]]
modId="terrablender"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ancient_aether]]
modId="aeroblender"
mandatory=true
versionRange="[1.0.1,)"
ordering="AFTER"
side="BOTH"