modLoader="javafml"
loaderVersion="[45,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"

[[mods]]
modId="ancient_aether"
version="${file.jarVersion}"
displayName="Ancient Aether"
logoFile="examplemod.png"
credits="Credit goes to Tuneful Turnip for making the Cactus Generation. Credit also goes to Zepalesque and all the other people that helped and gave me feedback on the Aether Project Discord Server. Also thanks to Unroman for the Ukranian Translation"
authors="Builderdog"
description='''
Ancient Aether is an Aether Add-On that adds new Ancient Valkyrie Structures aswell as unique biomes. There are also a ton of new Quality of Life things like Aether Quartz Ore, Aether Lanterns and Quicksoil Bricks. A lot more content is planned like a new Boss with a new progression system using the new Ancient Valkyrie Structures. This mod requires: Gecko Lib, Terrablender and Aeroblender. It is compatible with every other Aether Add-On.
'''
[[dependencies.ancient_aether]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.ancient_aether]]
modId="aether"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.examplemod]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"