modLoader = "javafml"
loaderVersion = "[1,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"

[[mods]]
modId = "ancient_aether"
version = "0.10.0"
displayName = "Ancient Aether"
logoFile = "ancient_aether.png"
credits = "Contributors: TunefulTurnip, Zepalesque | Translators: unroman, taizazanek, YuJianghan"
authors = "Builderdog"
description = "An exploration Aether Add-On that aims to overhaul the original ideas with modern takes."

[[mixins]]
config = "ancient_aether.mixins.json"